### ISSUE TITLE
Enhancement Request - Go to definition

### ISSUE THREAD

**Issue by njfm** [austin-----/code-gnu-global#2]
Not sure if this easy to implement or if it has major interest from others users (but I think it would be a real good enhancement):
- Is it it possible, at the the "Go to definition option", if the command "global --encode-path -xa" returns more than one line, to show a list of the all the definitions found (like it happens when we use the "Find All References")?

**Comment by austin-----** [comment]
Hi @njfm, thanks for the feedback. The VSCode definition provider API wants only one location instead of a list of locations, that is why we only return one definition from the extension. The real problem is that: gnu global does not have any semantic info to know for sure which exact definition is for the current context. We need more than a tagging tool for this purpose (like Clang).

**Comment by austin-----** [comment]
@njfm, after a second thought. I figured there is a way to show a list of definition candidates. Published a new version to do this. Again, thanks for the feedback.

**Comment by njfm** [comment]
Thanks... The fix is great and allows me to travel to the correct definition!
